### ISSUE TITLE
Compatibility Issue with react-native-reanimated 3.3.0 and Expo SDK 49

### ISSUE THREAD

**Issue by Skyfiir78** [hoangvu12/expo-skeleton-loader#2]
Bonjour 👋,

I'm currently experiencing a compatibility issue when using expo-skeleton-loader with Expo SDK 49 and react-native-reanimated version 3.3.0. The error message displayed is as follows:

```
Error: [Reanimated] Mismatch between JavaScript part and native part of Reanimated (3.3.0 vs. 2.14.3). Did you forget to re-build the app after upgrading react-native-reanimated? If you use Expo Go, you must downgrade to 2.14.3 which is bundled into Expo SDK., js engine: hermes
```

This error suggests a mismatch between the versions of react-native-reanimated used by Expo and expo-skeleton-loader. Since Expo SDK 49 seems to be compatible with react-native-reanimated 3.3.0, it appears that expo-skeleton-loader might still be depending on an older version of react-native-reanimated.

Steps to Reproduce
Upgrade an Expo project to SDK 49.
Install react-native-reanimated 3.3.0.
Integrate and run expo-skeleton-loader within the project.
Observe the error upon running the app.
Expected Behavior
The expo-skeleton-loader should work seamlessly with Expo SDK 49 and react-native-reanimated 3.3.0 without causing version mismatch errors.

Suggested Solution
It would be greatly appreciated if expo-skeleton-loader could be updated to support react-native-reanimated version 3.3.0, ensuring compatibility with Expo SDK 49.

**Comment by hoangvu12** [comment]
Hey, I'm glad that you are interested in my library.

Unfortunately, I stopped working on this library over 2 years ago, and I have no intention of maintaining it.
There are similar libraries that I recommend you to try::

[react-native-skeleton-placeholder](https://www.npmjs.com/package/react-native-skeleton-placeholder)
[react-native-skeleton-content](https://www.npmjs.com/package/react-native-skeleton-content)
